#!/usr/bin/env escript
% -*- erlang -*- vim: set filetype=erlang :

% Do Reverse Words in Erlang.
%
% The input file will be the first command line argument,
% print your output to stdout.
%
% Here's some relevent documentation:
%   http://www.erlang.org/doc/man/file.html
%   http://www.erlang.org/doc/man/lists.html
%   http://www.erlang.org/doc/man/string.html

main(Args) ->
    {ok,File} = file:open(Args,[read]),
    string:strip(io:get_line(File,""),right,10),
    AllLines = read_all_lines(File),
    ReversedWords = lists:map(fun(X) -> reverse_words(X) end,AllLines),
    print_all(ReversedWords,1).

read_all_lines(File) ->
    Data = io:get_line(File,""),
    if
        Data == eof -> [];
        Data /= eof -> [string:strip(Data,right,10)|read_all_lines(File)]
    end.

reverse_words(Xs) ->
    string:join(lists:reverse(string:tokens(Xs," "))," ").
    
print_all([],_) -> [];
print_all([X|Xs],N) ->
    io:format("Case #~p: ~s~n",[N,X]),
    print_all(Xs,N+1).
